# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 210)
        MainWindow.setMinimumSize(QtCore.QSize(390, 210))
        MainWindow.setMaximumSize(QtCore.QSize(390, 210))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(20, 120, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button.setFont(font)
        self.button.setStyleSheet("color: rgb(255, 255, 255);")
        self.button.setObjectName("button")
        self.tE_Answer = QtWidgets.QTextEdit(self.centralwidget)
        self.tE_Answer.setGeometry(QtCore.QRect(150, 120, 120, 60))
        self.tE_Answer.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tE_Answer.setFont(font)
        self.tE_Answer.setStyleSheet("color: rgb(255, 255, 255);")
        self.tE_Answer.setReadOnly(True)
        self.tE_Answer.setObjectName("tE_Answer")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 40, 377, 42))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tE_A = QtWidgets.QTextEdit(self.widget)
        self.tE_A.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tE_A.setFont(font)
        self.tE_A.setStyleSheet("color: rgb(255, 255, 255);")
        self.tE_A.setObjectName("tE_A")
        self.horizontalLayout.addWidget(self.tE_A)
        self.l_x2 = QtWidgets.QLabel(self.widget)
        self.l_x2.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_x2.setFont(font)
        self.l_x2.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.l_x2.setObjectName("l_x2")
        self.horizontalLayout.addWidget(self.l_x2)
        self.tE_B = QtWidgets.QTextEdit(self.widget)
        self.tE_B.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tE_B.setFont(font)
        self.tE_B.setStyleSheet("color: rgb(255, 255, 255);")
        self.tE_B.setObjectName("tE_B")
        self.horizontalLayout.addWidget(self.tE_B)
        self.l_x = QtWidgets.QLabel(self.widget)
        self.l_x.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_x.setFont(font)
        self.l_x.setStyleSheet("\n"
"background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.l_x.setObjectName("l_x")
        self.horizontalLayout.addWidget(self.l_x)
        self.tE_C = QtWidgets.QTextEdit(self.widget)
        self.tE_C.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tE_C.setFont(font)
        self.tE_C.setStyleSheet("color: rgb(255, 255, 255);")
        self.tE_C.setObjectName("tE_C")
        self.horizontalLayout.addWidget(self.tE_C)
        self.l_zero = QtWidgets.QLabel(self.widget)
        self.l_zero.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l_zero.setFont(font)
        self.l_zero.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.l_zero.setObjectName("l_zero")
        self.horizontalLayout.addWidget(self.l_zero)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 390, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Квадратное уравнение!"))
        self.button.setText(_translate("MainWindow", "ОТВЕТ"))
        self.l_x2.setText(_translate("MainWindow", "  X^2 +"))
        self.l_x.setText(_translate("MainWindow", "     X  +"))
        self.l_zero.setText(_translate("MainWindow", "  =  0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
